[mysqld]
basedir=C:/Program Files/MySQL/MySQL Server 8.4
datadir=C:/program1/shiftpop0/Prism/prism-app/.mysql/data
port=3306
bind-address=127.0.0.1
mysqlx=0
log-error=C:/program1/shiftpop0/Prism/prism-app/.mysql/mysql.err
tmpdir=C:/program1/shiftpop0/Prism/prism-app/.mysql/tmp

[client]
port=3306
